FROM python:3.10.13-alpine3.18

WORKDIR /src

COPY requirements.prod.txt requirements.prod.txt

RUN pip install --no-cache-dir -r requirements.prod.txt

COPY requirements.dev.txt requirements.dev.txt

RUN pip install --no-cache-dir -r requirements.dev.txt

COPY . .

# RUN python3 -m build
RUN pip install --no-cache-dir .
