---
name: Verso gate keeper pipeline
on: [push]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Install prerequisites
        run: sudo snap install --edge --classic just
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Run all checks and tests
        run: just test
